environments:
  - dev
  - prod

stages:
  ingest:
    privileges:
      dev:
        read:
          - developer
        write:
          - ingest
      prod:
        write:
          - ingest
  clean:
    privileges:
      dev:
        read:
          - developer
        write:
          - developer
      prod:
        read:
          - developer
        write:
          - developer
  normalize:
    privileges:
      dev:
        read:
          - reporting
        write:
          - developer
      prod:
        read:
          - reporting
        write:
          - developer
  integrate:
    privileges:
      dev:
        read:
          - reporting
        write:
          - developer
      prod:
        read:
          - reporting
        write:
          - developer
  analyze:
    privileges:
      dev:
        read:
          - reporting
        write:
          - analyst
      prod:
        read:
          - reporting
        write:
          - analyst

roles:
  sysadmin:
    granted_roles:
      - dba
  dba:
    granted_roles:
      - automation
  automation:
    granted_roles:
      - ingest
      - developer
  developer:
    granted_roles:
      - analyst
  analyst:
    granted_roles:
      - reporting

users:
  dbt_cloud:
    granted_roles:
      - automation
  fivetran:
    granted_roles:
      - ingest
  craig:
    granted_roles:
      - dba
      - developer
      - analyst
      - reporting

warehouses:
  x-small:
    privileges:
      - automation
      - ingest
      - developer
      - analyst
      - reporting
  small:
    privileges:
      - automation
      - ingest
  medium:
    privileges:
      - automation
  large:
    privileges:
      - automation
